name: Release on tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build --if-present

      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          if [ -d dist ]; then
            zip -r artifacts/dist.zip dist
          else
            echo "No se encontró directorio dist tras el build" && exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: artifacts/dist.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/dist.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
